Fixed a typo!

diff --git a/msddsbunch b/msddsbunch
--- a/msddsbunch
+++ b/msddsbunch
@@ -77,7 +77,7 @@ while true; do
         --xy_cutoff) xy_cutoff=$2; shift 2;;
         --z_cutoff) z_cutff=$2; shift 2;;
         --) break;;
-        *) echo -e "\nError: Unknow argument $1!"; exit 1;;
+        *) echo -e "\nError: Unknown argument $1!"; exit 1;;
     esac
 done
 
